services:
  - type: web
    name: x1-api
    env: python
    plan: free
    buildCommand: |
      apt-get update && \
      apt-get install -y libgtk-4-1 libgraphene-1.0-0 libgstgl-1.0-0 libgstcodecparsers-1.0-0 libavif15 libenchant-2-2 libsecret-1-0 libmanette-0.2-0 libgles2 && \
      pip install -r requirements.txt && playwright install
    startCommand: python3 roster_api.py